AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'it', 'let', 'let!', 'before', 'after']
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/Documentation:
  Enabled: false
